// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

package com.boloutaredoubeni.twentyfortyeight.djinni;

public enum Move {
    UP,
    DOWN,
    LEFT,
    RIGHT,
    ;
}
