// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#pragma once

#include "GameStateChangedListener.hpp"
#include "djinni_support.hpp"

namespace twentyfortyeight { namespace jni {

class GameStateChangedListener final : ::djinni::JniInterface<::twentyfortyeight::cpp::GameStateChangedListener, GameStateChangedListener> {
public:
    using CppType = std::shared_ptr<::twentyfortyeight::cpp::GameStateChangedListener>;
    using CppOptType = std::shared_ptr<::twentyfortyeight::cpp::GameStateChangedListener>;
    using JniType = jobject;

    using Boxed = GameStateChangedListener;

    ~GameStateChangedListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<GameStateChangedListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<GameStateChangedListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    GameStateChangedListener();
    friend ::djinni::JniClass<GameStateChangedListener>;
    friend ::djinni::JniInterface<::twentyfortyeight::cpp::GameStateChangedListener, GameStateChangedListener>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::twentyfortyeight::cpp::GameStateChangedListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void OnGameStateChanged() override;

    private:
        friend ::djinni::JniInterface<::twentyfortyeight::cpp::GameStateChangedListener, ::twentyfortyeight::jni::GameStateChangedListener>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/boloutaredoubeni/twentyfortyeight/djinni/GameStateChangedListener") };
    const jmethodID method_onGameStateChanged { ::djinni::jniGetMethodID(clazz.get(), "onGameStateChanged", "()V") };
};

} }  // namespace twentyfortyeight::jni
