// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from game_state.idl

#pragma once

#include "GameState.hpp"
#include "djinni_support.hpp"

namespace twentyfortyeight { namespace jni {

class GameState final : ::djinni::JniInterface<::twentyfortyeight::cpp::GameState, GameState> {
public:
    using CppType = std::shared_ptr<::twentyfortyeight::cpp::GameState>;
    using CppOptType = std::shared_ptr<::twentyfortyeight::cpp::GameState>;
    using JniType = jobject;

    using Boxed = GameState;

    ~GameState();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<GameState>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<GameState>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    GameState();
    friend ::djinni::JniClass<GameState>;
    friend ::djinni::JniInterface<::twentyfortyeight::cpp::GameState, GameState>;

};

} }  // namespace twentyfortyeight::jni
