// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#include "GameStateChangedListener.hpp"  // my header

namespace twentyfortyeight { namespace jni {

GameStateChangedListener::GameStateChangedListener() : ::djinni::JniInterface<::twentyfortyeight::cpp::GameStateChangedListener, GameStateChangedListener>() {}

GameStateChangedListener::~GameStateChangedListener() = default;

GameStateChangedListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

GameStateChangedListener::JavaProxy::~JavaProxy() = default;

void GameStateChangedListener::JavaProxy::OnGameStateChanged() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::twentyfortyeight::jni::GameStateChangedListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onGameStateChanged);
    ::djinni::jniExceptionCheck(jniEnv);
}

} }  // namespace twentyfortyeight::jni
