// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#include "player.hpp"  // my header
#include "Marshal.hpp"
#include "move.hpp"
#include "player.hpp"

namespace twentyfortyeight { namespace jni {

Player::Player() : ::djinni::JniInterface<::twentyfortyeight::cpp::Player, Player>("com/boloutaredoubeni/twentyfortyeight/djinni/Player$CppProxy") {}

Player::~Player() = default;


CJNIEXPORT void JNICALL Java_com_boloutaredoubeni_twentyfortyeight_djinni_Player_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::twentyfortyeight::cpp::Player>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_boloutaredoubeni_twentyfortyeight_djinni_Player_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::twentyfortyeight::cpp::Player::Create();
        return ::djinni::release(::twentyfortyeight::jni::Player::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_boloutaredoubeni_twentyfortyeight_djinni_Player_00024CppProxy_native_1moveTile(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_move, jbyte j_from)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::twentyfortyeight::cpp::Player>(nativeRef);
        ref->MoveTile(::twentyfortyeight::jni::Move::toCpp(jniEnv, j_move),
                      ::djinni::I8::toCpp(jniEnv, j_from));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_boloutaredoubeni_twentyfortyeight_djinni_Player_00024CppProxy_native_1newGame(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::twentyfortyeight::cpp::Player>(nativeRef);
        ref->NewGame();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_boloutaredoubeni_twentyfortyeight_djinni_Player_00024CppProxy_native_1endGame(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::twentyfortyeight::cpp::Player>(nativeRef);
        ref->EndGame();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

} }  // namespace twentyfortyeight::jni
