// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#include "Player.hpp"  // my header
#include "GameStateChangedListener.hpp"
#include "Move.hpp"

namespace twentyfortyeight { namespace jni {

Player::Player() : ::djinni::JniInterface<::twentyfortyeight::cpp::Player, Player>("com/boloutaredoubeni/twentyfortyeight/djinni/Player$CppProxy") {}

Player::~Player() = default;


CJNIEXPORT void JNICALL Java_com_boloutaredoubeni_twentyfortyeight_djinni_Player_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::twentyfortyeight::cpp::Player>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_boloutaredoubeni_twentyfortyeight_djinni_Player_00024CppProxy_native_1create(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_listener)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::twentyfortyeight::cpp::Player>(nativeRef);
        ref->Create(::twentyfortyeight::jni::GameStateChangedListener::toCpp(jniEnv, j_listener));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_boloutaredoubeni_twentyfortyeight_djinni_Player_00024CppProxy_native_1moveTile(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_move)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::twentyfortyeight::cpp::Player>(nativeRef);
        ref->MoveTile(::twentyfortyeight::jni::Move::toCpp(jniEnv, j_move));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_boloutaredoubeni_twentyfortyeight_djinni_Player_00024CppProxy_native_1newGame(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::twentyfortyeight::cpp::Player>(nativeRef);
        ref->NewGame();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_boloutaredoubeni_twentyfortyeight_djinni_Player_00024CppProxy_native_1endGame(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::twentyfortyeight::cpp::Player>(nativeRef);
        ref->EndGame();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

} }  // namespace twentyfortyeight::jni
