// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.djinni

#pragma once

#include "djinni_support.hpp"
#include "player.hpp"

namespace twenty48 { namespace jni {

class player final : ::djinni::JniInterface<::twenty48::cpp::Player, player> {
public:
    using CppType = std::shared_ptr<::twenty48::cpp::Player>;
    using CppOptType = std::shared_ptr<::twenty48::cpp::Player>;
    using JniType = jobject;

    using Boxed = player;

    ~player();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<player>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<player>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    player();
    friend ::djinni::JniClass<player>;
    friend ::djinni::JniInterface<::twenty48::cpp::Player, player>;

};

} }  // namespace twenty48::jni
