// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.djinni

package com.boloutaredoubeni.twenty48.djinni;

public enum Move {
    UP,
    DOWN,
    LEFT,
    RIGHT,
    ;
}
