// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, T48Move) {
  T48MoveUp,
  T48MoveDown,
  T48MoveLeft,
  T48MoveRight,
};
