// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.djinni

#import "T48Move.h"
#import <Foundation/Foundation.h>
@class T48Player;

@interface T48Player : NSObject

+ (nullable T48Player *)create;

- (void)newGame;

- (int64_t)score;

- (BOOL)hasWon;

- (nonnull NSArray<NSNumber *> *)gameState;

- (BOOL)gameOver;

/**
 * @param move the direction of movement
 * @return bool false if the move was unsuccessful
 */
- (BOOL)swipe:(T48Move)move;

@end
