# NOTE: just for design, will be deleted
game_state = interface +c {
  score(): i16;
  draw();
  win(): bool;
}

move = enum {
  up;
  down;
  left;
  right;
}

player = interface +c {
  static create(): player;
  move_tile(move: move, from: i8);
  new_game();
  end_game();
}

game_change_listener = interface +o +j {
  on_game_state_changed();
}
