// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <vector>

namespace twenty48 {

enum class Move;

class Player {
public:
    virtual ~Player() {}

    static std::shared_ptr<Player> Create();

    virtual void NewGame() = 0;

    virtual int64_t Score() = 0;

    virtual bool HasWon() = 0;

    virtual std::vector<int32_t> GameState() = 0;

    virtual bool GameOver() = 0;

    /**
     * @param move the direction of movement
     * @return bool false if the move was unsuccessful
     */
    virtual bool Swipe(Move move) = 0;

    virtual int64_t MovesMade() = 0;
};

}  // namespace twenty48
