// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from game_state.idl

#import <Foundation/Foundation.h>


@interface TFEGameState : NSObject

- (int16_t)score;

- (void)draw;

@end
