// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#import <Foundation/Foundation.h>


@protocol TFEGameStateChangedListener

- (void)onGameStateChanged;

@end
