// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, TFEMove)
{
    TFEMoveUp,
    TFEMoveDown,
    TFEMoveLeft,
    TFEMoveRight,
};
