// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.djinni

#import "TFEMove.h"
#import <Foundation/Foundation.h>
@class TFEPlayer;


@interface TFEPlayer : NSObject

+ (nullable TFEPlayer *)create;

- (void)newGame;

- (int64_t)score;

- (BOOL)hasWon;

- (nonnull NSArray<NSNumber *> *)gameState;

- (BOOL)gameOver;

/** returns false if the move was unsuccessful */
- (BOOL)swipe:(TFEMove)move;

@end
