// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#import "TFEMove.h"
#import <Foundation/Foundation.h>
@class TFEPlayer;


@interface TFEPlayer : NSObject

+ (nullable TFEPlayer *)create;

- (void)moveTile:(TFEMove)move
            from:(int8_t)from;

- (void)newGame;

- (void)endGame;

@end
