// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#pragma once

namespace twentyfortyeight { namespace cpp {

class GameStateChangedListener {
public:
    virtual ~GameStateChangedListener() {}

    virtual void OnGameStateChanged() = 0;
};

} }  // namespace twentyfortyeight::cpp
