// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from game_state.idl

#pragma once

#include <cstdint>

namespace twentyfortyeight { namespace cpp {

class GameState {
public:
    virtual ~GameState() {}

    virtual int16_t Score() = 0;

    virtual void Draw() = 0;
};

} }  // namespace twentyfortyeight::cpp
