// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#pragma once

#include <cstdint>

namespace twentyfortyeight { namespace cpp {

/** NOTE: just for design, will be deleted */
class GameState {
public:
    virtual ~GameState() {}

    virtual int16_t Score() = 0;

    virtual void Draw() = 0;

    virtual bool Win() = 0;
};

} }  // namespace twentyfortyeight::cpp
