// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.djinni

#pragma once

namespace twenty48 { namespace cpp {

enum class Move : int {
    Up,
    Down,
    Left,
    Right,
};

} }  // namespace twenty48::cpp
