// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.djinni

#pragma once

namespace twentyfortyeight { namespace cpp {

enum class Move : int {
    Up,
    Down,
    Left,
    Right,
};

} }  // namespace twentyfortyeight::cpp
