// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.djinni

#pragma once

#include <functional>

namespace twentyfortyeight { namespace cpp {

enum class Move : int {
    UP,
    DOWN,
    LEFT,
    RIGHT,
};

} }  // namespace twentyfortyeight::cpp

namespace std {

template <>
struct hash<::twentyfortyeight::cpp::Move> {
    size_t operator()(::twentyfortyeight::cpp::Move type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
