// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#pragma once

#include <cstdint>
#include <memory>

namespace twentyfortyeight { namespace cpp {

enum class Move;

class Player {
public:
    virtual ~Player() {}

    static std::shared_ptr<Player> Create();

    virtual void MoveTile(Move move, int8_t from) = 0;

    virtual void NewGame() = 0;

    virtual void EndGame() = 0;
};

} }  // namespace twentyfortyeight::cpp
