// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#include "GameStateChangedListener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol TFEGameStateChangedListener;

namespace twentyfortyeight { namespace objc {

class GameStateChangedListener
{
public:
    using CppType = std::shared_ptr<::twentyfortyeight::cpp::GameStateChangedListener>;
    using CppOptType = std::shared_ptr<::twentyfortyeight::cpp::GameStateChangedListener>;
    using ObjcType = id<TFEGameStateChangedListener>;

    using Boxed = GameStateChangedListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} }  // namespace twentyfortyeight::objc

