// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#include "game_state.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TFEGameState;

namespace twentyfortyeight { namespace objc {

class GameState
{
public:
    using CppType = std::shared_ptr<::twentyfortyeight::cpp::GameState>;
    using CppOptType = std::shared_ptr<::twentyfortyeight::cpp::GameState>;
    using ObjcType = TFEGameState*;

    using Boxed = GameState;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} }  // namespace twentyfortyeight::objc

