// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#import "TFEGameChangeListener+Private.h"
#import "TFEGameChangeListener.h"
#import "DJIObjcWrapperCache+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace twentyfortyeight { namespace objc {

class GameChangeListener::ObjcProxy final
: public ::twentyfortyeight::cpp::GameChangeListener
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void OnGameStateChanged() override
    {
        @autoreleasepool {
            [Handle::get() onGameStateChanged];
        }
    }
};

} }  // namespace twentyfortyeight::objc

namespace twentyfortyeight { namespace objc {

auto GameChangeListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto GameChangeListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

} }  // namespace twentyfortyeight::objc
