// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.idl

#include "game_change_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol TFEGameChangeListener;

namespace twentyfortyeight { namespace objc {

class GameChangeListener
{
public:
    using CppType = std::shared_ptr<::twentyfortyeight::cpp::GameChangeListener>;
    using CppOptType = std::shared_ptr<::twentyfortyeight::cpp::GameChangeListener>;
    using ObjcType = id<TFEGameChangeListener>;

    using Boxed = GameChangeListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} }  // namespace twentyfortyeight::objc

