// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from game_state.idl

#import "TFEGameState+Private.h"
#import "TFEGameState.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface TFEGameState ()

- (id)initWithCpp:(const std::shared_ptr<::twentyfortyeight::cpp::GameState>&)cppRef;

@end

@implementation TFEGameState {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::twentyfortyeight::cpp::GameState>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::twentyfortyeight::cpp::GameState>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (int16_t)score {
    try {
        auto r = _cppRefHandle.get()->Score();
        return ::djinni::I16::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)draw {
    try {
        _cppRefHandle.get()->Draw();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace twentyfortyeight { namespace objc {

auto GameState::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto GameState::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<TFEGameState>(cpp);
}

} }  // namespace twentyfortyeight::objc

@end
