// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from twenty_forty_eight.djinni

#include "player.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TFEPlayer;

namespace twentyfortyeight { namespace objc {

class Player
{
public:
    using CppType = std::shared_ptr<::twentyfortyeight::cpp::Player>;
    using CppOptType = std::shared_ptr<::twentyfortyeight::cpp::Player>;
    using ObjcType = TFEPlayer*;

    using Boxed = Player;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} }  // namespace twentyfortyeight::objc

